name: Terraform CI/CD global

on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'dev'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./global

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Choose Terraform workspace
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Switching to prod workspace"
            terraform workspace select prod || terraform workspace new prod
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "Switching to staging workspace"
            terraform workspace select staging || terraform workspace new staging
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "Switching to dev workspace"
            terraform workspace select dev || terraform workspace new dev
          else
            echo "No matching branch found"
          fi

      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }}
      
      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
